### ISSUE TITLE
Any clue at a timeline?

### ISSUE THREAD

**Issue by BHare1985** [WebAssembly/memory64#20]
When can we expect 64-bit memory indexes?  Guesses are welcomed

Specifically, such that [Internet Computer canisters can use more than 4 GB of memory](https://forum.dfinity.org/t/abstract-away-the-4gb-canister-memory-limit/2084/)

**Comment by aardappel** [comment]
There is no single moment when 64-bit is "done" since there are many projects involved.

- LLVM (Clang/LLD), WABT, Binaryen: if you rely only on these tools, you can possibly use `wasm64` TODAY. There might still be bugs, but things are looking pretty good.
- Rust Wasm seems to support it now, but that's just the compiler, probably not in any bindings yet.
- Emscripten: in progress. I have no idea when this will be finished, I am hoping an initial version will at most take a few months. But given the sprawling nature of the project, I expect there to be quite a few issues to work thru for a while.
- V8: in progress, eta unknown.
- Other runtimes: unknown.
- Spec and Spec interpreter: close to done, but the proposal is in phase 3, and it's not "done" until phase 5.

I have no idea how Dfinity uses Wasm, what external tools does it need for wasm64 to function?

**Comment by lars-t-hansen** [comment]
Firefox: in progress, eta unknown.

**Comment by rossberg** [comment]
Dfinity uses Wasmtime, so we'd depend on that. And it currently provides a Rust and a Motoko SDK. The latter doesn't have any essential external dependencies.

@BHare1985, that said, there are additional hurdles to adopting 64-bit memories on the IC, such as persistence. And as mentioned on the thread you link to, it would not magically solve scalability for apps. What IC apps would actually benefit more from is [multiple memories](https://github.com/WebAssembly/multi-memory/blob/master/proposals/multi-memory/Overview.md), in order to make the use of stable memory more efficient.
